"""Generate the OOD ablation notebook (PDF/RFP + Spark log extraction)."""
import json
from pathlib import Path

WHEEL = "fabric_rlm-0.1.11.dev5-py3-none-any.whl"
WHEEL_PATH = f"/lakehouse/default/Files/fabric_rlm_longcot/wheels/{WHEEL}"

cells = [
    {"cell_type":"code","metadata":{},"execution_count":None,"outputs":[],"source":[
        "%%configure -f\n",
        '{"vCores": 4, "defaultLakehouse": {"name": "diagnostic", "id": "9d10bce5-1edc-4875-83c4-ac0a98a02775", "workspaceId": "82ad2591-974a-4ad4-ace6-e24879274a4b"}}',
    ]},
    {"cell_type":"markdown","metadata":{},"source":[
        "# fabric-rlm 0.1.11.dev5 — **3-way PVR ablation** (off vs reflect_only vs full)\n",
        "\n",
        "Tests whether dropping PLAN/VERIFY skill scaffolding while keeping the\n",
        "REFLECT mechanism (Honor PRIOR_ATTEMPT_FEEDBACK + `_with_feedback`\n",
        "synthesis + runtime reflection turn) preserves the PVR wins. Each case\n",
        "runs under `FABRIC_RLM_PVR_MODE` ∈ {off, reflect_only, full} with **fresh\n",
        "bandit state** per condition.\n",
    ]},
    {"cell_type":"code","metadata":{},"execution_count":None,"outputs":[],"source":[
        "import os, sys, json, time, traceback, uuid, platform as _platform, subprocess\n",
        "from pathlib import Path\n",
        "WHEEL_PATH = '" + WHEEL_PATH + "'\n",
        "TIER = 'pvr_ood_ablation'\n",
        "RUN_ID = time.strftime('%Y%m%d-%H%M%S') + '-' + uuid.uuid4().hex[:6]\n",
        "FILES_ROOT = Path('/lakehouse/default/Files')\n",
        "RUN_ROOT = FILES_ROOT / 'fabric_rlm_adaptive_validation' / TIER / RUN_ID\n",
        "RUN_ROOT.mkdir(parents=True, exist_ok=True)\n",
        "SUMMARY_PATH = RUN_ROOT / 'summary.json'\n",
        "summary = {'tier': TIER, 'run_id': RUN_ID, 'started_at': time.time(),\n",
        "           'python': _platform.python_version(), 'wheel': WHEEL_PATH,\n",
        "           'stages': [], 'ablation': {'cases': []}}\n",
        "def write_summary():\n",
        "    summary['elapsed_seconds'] = time.time() - summary['started_at']\n",
        "    SUMMARY_PATH.write_text(json.dumps(summary, indent=2, default=str))\n",
        "def stage(name, **info):\n",
        "    summary['stages'].append({'stage': name, 't': round(time.time()-summary['started_at'],1), **info})\n",
        "    write_summary(); print('[stage]', name, info)\n",
        "stage('setup', run_root=str(RUN_ROOT))\n",
        "subprocess.check_call(['pip','install','--quiet','--force-reinstall','--no-deps', WHEEL_PATH])\n",
        "stage('pip_wheel', done=True)\n",
        "subprocess.check_call(['pip','install','--quiet','dspy>=3.0.4'])\n",
        "stage('pip_dspy', done=True)\n",
        "import dspy, fabric_rlm\n",
        "stage('imported', dspy=dspy.__version__, fabric_rlm=fabric_rlm.__version__)\n",
    ]},
    {"cell_type":"code","metadata":{},"execution_count":None,"outputs":[],"source":[
        "FIX = FILES_ROOT / 'fabric_rlm_adaptive_validation' / 'fixtures'\n",
        "rfp_text = (FIX / 'rfp_sample_100k.txt').read_text(encoding='utf-8', errors='ignore')\n",
        "spark_text = (FIX / 'spark_log_sample_200k.json').read_text(encoding='utf-8', errors='ignore')\n",
        "stage('fixtures_loaded', rfp_chars=len(rfp_text), spark_chars=len(spark_text))\n",
        "\n",
        "RFP_QUESTION = (\n",
        "    'You are given the partial text of a 2025 Request for Proposal document. '\n",
        "    'Extract the following four fields and return ONLY a single JSON object '\n",
        "    'with exactly these keys: date_of_issue, response_due, authority, letter_of_credit_percent. '\n",
        "    'date_of_issue and response_due must be ISO format YYYY-MM-DD. '\n",
        "    'authority is the issuing organization name. '\n",
        "    'letter_of_credit_percent is the integer percent of the Fixed Management Fee required as a Letter of Credit.\\n\\n'\n",
        "    '--- RFP TEXT ---\\n' + rfp_text\n",
        ")\n",
        "SPARK_QUESTION = (\n",
        "    'You are given the first 200KB of a Spark event log (newline-delimited JSON events). '\n",
        "    'Extract the following five fields and return ONLY a single JSON object with exactly these keys: '\n",
        "    'spark_version, app_id, app_name, n_executors_added, gluten_version. '\n",
        "    'n_executors_added is the integer count of SparkListenerExecutorAdded events found in the log slice.\\n\\n'\n",
        "    '--- SPARK LOG ---\\n' + spark_text\n",
        ")\n",
        "\n",
        "CASES = [\n",
        "    {'id':'rfp-extract', 'template':'rfp_extract', 'difficulty':'ood',\n",
        "     'question': RFP_QUESTION,\n",
        "     'truth': {'date_of_issue':'2025-02-13','response_due':'2025-03-31',\n",
        "               'authority_must_contain':'victoria',\n",
        "               'letter_of_credit_percent':5}},\n",
        "    {'id':'spark-extract','template':'spark_extract','difficulty':'ood',\n",
        "     'question': SPARK_QUESTION,\n",
        "     'truth': {'spark_version':'3.5.5.5.4.20251218.3',\n",
        "               'app_id':'application_1769950908745_0001',\n",
        "               'app_name_must_contain':'EHS_DATA_MASTER_NOTEBOOK',\n",
        "               'n_executors_added':1,\n",
        "               'gluten_version':'1.3.0-20251127.2'}},\n",
        "]\n",
        "stage('cases_built', n=len(CASES))\n",
    ]},
    {"cell_type":"code","metadata":{},"execution_count":None,"outputs":[],"source":[
        "import re\n",
        "def parse_json_answer(s):\n",
        "    if not s: return None\n",
        "    s = s.strip()\n",
        "    m = re.search(r'\\{[\\s\\S]*\\}', s)\n",
        "    if not m: return None\n",
        "    try: return json.loads(m.group(0))\n",
        "    except Exception:\n",
        "        try: return json.loads(m.group(0).replace(\"'\",'\"'))\n",
        "        except Exception: return None\n",
        "\n",
        "def make_validator(case):\n",
        "    truth = case['truth']\n",
        "    def validator(result):\n",
        "        if not result.submitted or not result.payload: return False\n",
        "        ans = result.payload.get('answer') or ''\n",
        "        obj = parse_json_answer(ans if isinstance(ans,str) else json.dumps(ans))\n",
        "        if not isinstance(obj, dict): return False\n",
        "        for key, expected in truth.items():\n",
        "            if key.endswith('_must_contain'):\n",
        "                actual_key = key[:-len('_must_contain')]\n",
        "                v = obj.get(actual_key, '')\n",
        "                if not isinstance(v, str) or expected.lower() not in v.lower():\n",
        "                    return False\n",
        "            else:\n",
        "                v = obj.get(key)\n",
        "                if isinstance(expected, int):\n",
        "                    try:\n",
        "                        if int(v) != expected: return False\n",
        "                    except Exception: return False\n",
        "                else:\n",
        "                    if str(v).strip() != str(expected).strip(): return False\n",
        "        return True\n",
        "    return validator\n",
        "stage('validator_built')\n",
    ]},
    {"cell_type":"code","metadata":{},"execution_count":None,"outputs":[],"source":[
        "from fabric_rlm import RLM, FabricLM\n",
        "from fabric_rlm.experimental import BanditState, EffortBanditPolicy\n",
        "\n",
        "os.environ['FABRIC_RLM_CAPTURE_TURNS'] = '1'  # capture per-attempt turns\n",
        "base_lm = FabricLM('gpt-5', reasoning_effort='minimal', cache=False)\n",
        "stage('lm_built', base='gpt-5', start_effort='minimal')\n",
        "\n",
        "CONDITIONS = [('off','off'), ('reflect_only','reflect_only'), ('on','full')]\n",
        "ablation = summary['ablation']\n",
        "\n",
        "for case in CASES:\n",
        "    case_record = {'id': case['id'], 'template': case['template'],\n",
        "                   'difficulty': case['difficulty'], 'conditions': {}}\n",
        "    ablation['cases'].append(case_record); write_summary()\n",
        "    for cond_name, mode_val in CONDITIONS:\n",
        "        os.environ['FABRIC_RLM_PVR_MODE'] = mode_val\n",
        "        os.environ.pop('FABRIC_RLM_PVR', None)\n",
        "        state = BanditState()\n",
        "        try:\n",
        "            validator = make_validator(case)\n",
        "            policy = EffortBanditPolicy(\n",
        "                state=state, task_key=case['template'], warmup=2,\n",
        "                base_lm_spec=base_lm, base_reasoning_effort='minimal',\n",
        "                parallel_rollouts=3,\n",
        "            )\n",
        "            rlm = RLM(\n",
        "                signature='question -> answer',\n",
        "                lm=base_lm, engine='adaptive',\n",
        "                adaptive=dict(policy=policy, validator=validator,\n",
        "                              max_attempts=6, parallel_rollouts=1),\n",
        "            )\n",
        "            t0 = time.perf_counter()\n",
        "            result = rlm.run({'question': case['question']})\n",
        "            elapsed = time.perf_counter() - t0\n",
        "            meta = (result.trajectory.metadata or {}).get('adaptive', {}) if result.trajectory else {}\n",
        "            attempts = meta.get('attempts', [])\n",
        "            passed = bool(result.submitted and validator(result))\n",
        "            cond_record = {\n",
        "                'passed': passed, 'submitted': result.submitted,\n",
        "                'elapsed_seconds': elapsed,\n",
        "                'starting_rung': attempts[0].get('rung') if attempts else None,\n",
        "                'winner_rung': meta.get('winner_rung'),\n",
        "                'stop_reason': meta.get('stop_reason'),\n",
        "                'n_attempts': len(attempts),\n",
        "                'total_prompt_tokens': sum(a.get('prompt_tokens') or 0 for a in attempts),\n",
        "                'total_completion_tokens': sum(a.get('completion_tokens') or 0 for a in attempts),\n",
        "                'final_answer_preview': (str((result.payload or {}).get('answer'))[:400]) if result.payload else None,\n",
        "                'attempts_summary': [\n",
        "                    {'rung': a.get('rung'), 'passed': a.get('passed'),\n",
        "                     'submitted': a.get('submitted'), 'turns_used': a.get('turns_used'),\n",
        "                     'failure_reason': a.get('failure_reason'),\n",
        "                     'feedback': (a.get('feedback') or '')[:300],\n",
        "                     'answer_preview': str(((a.get('payload_preview') or {}).get('answer')) or '')[:200]}\n",
        "                    for a in attempts\n",
        "                ],\n",
        "            }\n",
        "            traj_path = RUN_ROOT / f\"trajectory_{case['id']}_{cond_name}.jsonl\"\n",
        "            with traj_path.open('w', encoding='utf-8') as fh:\n",
        "                for ai, a in enumerate(attempts):\n",
        "                    fh.write(json.dumps({'attempt_index': ai, 'rung': a.get('rung'),\n",
        "                                         'passed': a.get('passed'), 'submitted': a.get('submitted'),\n",
        "                                         'failure_reason': a.get('failure_reason'),\n",
        "                                         'feedback': a.get('feedback'),\n",
        "                                         'turns': a.get('turns', [])}, ensure_ascii=False) + '\\n')\n",
        "            cond_record['trajectory_jsonl'] = str(traj_path.relative_to(FILES_ROOT))\n",
        "        except Exception as exc:\n",
        "            cond_record = {'passed': False, 'error': repr(exc), 'traceback': traceback.format_exc()}\n",
        "        case_record['conditions'][cond_name] = cond_record; write_summary()\n",
        "        stage('cond_done', case=case['id'], cond=cond_name,\n",
        "              passed=cond_record.get('passed'),\n",
        "              n_attempts=cond_record.get('n_attempts'),\n",
        "              elapsed=round(cond_record.get('elapsed_seconds') or 0, 1),\n",
        "              tokens=(cond_record.get('total_prompt_tokens',0)+cond_record.get('total_completion_tokens',0)))\n",
        "    stage('case_done', case=case['id'])\n",
        "\n",
        "ab_table = []\n",
        "for c in ablation['cases']:\n",
        "    row = {'case': c['id'], 'difficulty': c['difficulty']}\n",
        "    for cond_name in ('off','reflect_only','on'):\n",
        "        cd = c['conditions'].get(cond_name, {})\n",
        "        row[cond_name+'_passed'] = cd.get('passed')\n",
        "        row[cond_name+'_attempts'] = cd.get('n_attempts')\n",
        "        row[cond_name+'_elapsed'] = round(cd.get('elapsed_seconds') or 0, 1)\n",
        "        row[cond_name+'_tokens'] = (cd.get('total_prompt_tokens',0) or 0) + (cd.get('total_completion_tokens',0) or 0)\n",
        "    ab_table.append(row)\n",
        "summary['ab_table'] = ab_table; write_summary()\n",
        "stage('ablation_done', cases=len(ab_table))\n",
        "for r in ab_table: print(r)\n",
    ]},
]

nb = {
    "cells": cells,
    "metadata": {
        "kernelspec": {"display_name":"Python 3.11","language":"python","name":"python3"},
        "language_info":{"name":"python","version":"3.11"},
        "kernel_info":{"name":"jupyter","jupyter_kernel_name":"python3.11"},
        "dependencies":{"lakehouse":{"default_lakehouse":"9d10bce5-1edc-4875-83c4-ac0a98a02775","default_lakehouse_name":"diagnostic","default_lakehouse_workspace_id":"82ad2591-974a-4ad4-ace6-e24879274a4b"}},
    },
    "nbformat":4, "nbformat_minor":5,
}
out = Path("notebooks/pvr_ood_ablation_diag.ipynb")
out.write_text(json.dumps(nb, indent=1), encoding='utf-8')
print('wrote', out, 'cells:', len(cells))
